# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths:
      - '.github/workflows/pages.yml'
      - 'docs/**'
      - 'lsplant/src/main/jni/include/lsplant.hpp'
      - 'README.md'
      - 'README_zh.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          ssh-key: ${{ secrets.SSH_KEY }}
      - name: Install doxygen
        run: |
          curl -LO https://github.com/doxygen/doxygen/releases/download/Release_1_15_0/doxygen-1.15.0.linux.bin.tar.gz
          tar -zxf doxygen-1.15.0.linux.bin.tar.gz
      - name: Generate doxygen
        run: |
          release_version=$(curl -s https://api.github.com/repos/PeterFeicht/cppreference-doc/releases/latest | jq -r .tag_name)
          echo "Latest cppreference-doc version: $release_version"
          curl -LO "https://github.com/PeterFeicht/cppreference-doc/releases/download/$release_version/html-book-${release_version#v}.zip"
          unzip -o "html-book-${release_version#v}.zip" "cppreference-doxygen-web.tag.xml" -d ./docs

          ./doxygen-1.15.0/bin/doxygen docs/doxygen.cfg

          mkdir -p docs/docs/zh
          sed -i 's/OUTPUT_LANGUAGE        = English/OUTPUT_LANGUAGE        = Chinese/g' docs/doxygen.cfg
          sed -i 's/USE_MDFILE_AS_MAINPAGE = README.md/USE_MDFILE_AS_MAINPAGE = README_zh.md/g' docs/doxygen.cfg
          sed -i 's/HTML_OUTPUT            = docs/HTML_OUTPUT            = docs\/zh/g' docs/doxygen.cfg
          ./doxygen-1.15.0/bin/doxygen docs/doxygen.cfg
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'docs/docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
